openebs/upgrade

- pkg/upgrade/upgrader/cstor_cspc.go
- pkg/upgrade/upgrader/cstor_cspi.go
This PR enables the reconcile of the version from the operators' side. Once the reconcile framework is merged ref:https://github.com/openebs/cstor-operators/pull/60 we can merge this PR.
> reafct(upgrade): uncomment reconcile code

- Makefile
- build/migrate/Makefile.mk
Signed-off-by: kmova <kiran.mova@mayadata.io>
> fix(build): use env IMAGE_ORG as docker user name

- CHANGELOG.md
This PR adds changelog for the repo.
> chore(docs): add changelog file

- cmd/upgrade/executor/resource.go
- pkg/upgrade/patch/cspc.go
- pkg/upgrade/patch/cspi.go
- pkg/upgrade/patch/cv.go
- pkg/upgrade/patch/cvc.go
- pkg/upgrade/patch/cvr.go
- pkg/upgrade/patch/deployment.go
- pkg/upgrade/patch/service.go
- this PR fixes the version checks of resources taking
account of the custom version tags like 1.12.0-ce-RC1
- this PR also fixes the error overridden for utask upgrades
> fix(version): fix version checks of resources

- ci/upgrade/setup.sh
This PR updates the csi operator yaml to generic yaml.
> fix(tarvis): update generic csi operator yaml

- go.mod
- go.sum
- vendor/github.com/openebs/api/pkg/apis/cstor/v1/cstorpoolinstance.go
- vendor/modules.txt
This PR updates the vendor file to include latest changes made in cspc schema in openebs/api.
> chore(vendor): update latest openebs/api vendor files

- pkg/migrate/cstor/cspc_generator.go
- pkg/migrate/cstor/cspc_generator_test.go
This PR is cherry-pick for #38
> fix(migration): fix striped raid group config while migrating

- docs/migration.md
- docs/upgrade.md
- docs/verify_cstor_bds.sh
- docs/verifybds.sh
- docs/virtual-disk-troubleshoot.md
This PR adds troubleshooting doc for cStor pools using virtual disk blockdevices.
> chore(doc): add troubleshooting doc for virtual disk blockdevices

- ci/upgrade/cstor-operator.tmp.yaml
- ci/upgrade/pool.tmp.yaml
- ci/upgrade/sanity.sh
- ci/upgrade/setup.sh
- ci/upgrade/test.sh
- ci/upgrade/volume.tmp.yaml
This PR is cherry-pick for #44
> fix(travis): make upgrade sanity test configurable for different IMAGE_ORG

- pkg/migrate/cstor/cspc_generator.go
- pkg/migrate/cstor/cspc_generator_test.go
This PR is to cherry-pick #38 in 1.12.x branch.
> fix(migration): fix striped raid group config while migrating 

- go.mod
- go.sum
- pkg/migrate/cstor/cspc_generator.go
- vendor/github.com/openebs/api/pkg/apis/types/types.go
- vendor/modules.txt
This PR checks for bd-tag annotation on the spc and adds the same to cspc while migration.
> refact(cstor-pool): add bd-tag to cspc while migration

- pkg/version/util.go
> chore(upgrade): add valid current versions for 2.1.0 upgrades

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/pull_request_template.md
This PR solves the issue: https://github.com/openebs/openebs/issues/3144
> chore : Added PR and Issue template

- README.md
Hello I added the requested badges in readme.md file but I think there is no account is not created for'Codecov.
> Added all the badges in upgrade

- pkg/migrate/cstor/cspc_generator_test.go
Issue URL : https://github.com/openebs/openebs/issues/3143
> Replace reflect.DeepEqual() with "github.com/google/go-cmp/cmp"

- README.md
Updating `Readme.md` with Upgrade and Migration steps from respective docs folder  issue #3145 
contents are taken from below.
[upgrade](https://github.com/openebs/upgrade/blob/master/docs/upgrade.md)
[migrate](https://github.com/openebs/upgrade/blob/master/docs/migration.md)
> Update the main README with info and link upgrade & migration docs #3145

- docs/migration.md
- docs/upgrade.md
- examples/migrate/cstor-volume-migration.yaml
- examples/migrate/spc-migration.yaml
- examples/upgrade/cstor-cspc.yaml
- examples/upgrade/cstor-volume.yaml
This PR 
- updates the migration with the latest steps regarding virtual disks
- replaces the image-tags with the placeholders to avoid using wrong images
**Checklist**
> chore(docs): update docs with the latest steps

- ci/migrate/setup.sh
Now the ndm charts is a part of cstor-operators so the  sparse count is set to 0 by default. This PR fixes this issue.
**Checklist**
> fix(travis): update travis with the latest yamls

- ci/migrate/setup.sh
- docs/migration.md
- docs/upgrade.md
- examples/migrate/cstor-volume-migration.yaml
- examples/migrate/spc-migration.yaml
- examples/upgrade/cstor-cspc.yaml
- examples/upgrade/cstor-volume.yaml
This PR
- updates upgrade docs with 2.3.0 steps
- updates the images to latest multi-arch tags
**Checklist**
> chore(upgrade): update upgrade README with 2.3.0 steps

- CHANGELOG.md
- changelogs/released/v2.3.0-RC1/32-shubham14bajpai
- changelogs/released/v2.3.0-RC1/65-shubham14bajpai
- changelogs/released/v2.3.0-RC1/66-shubham14bajpai
This PR adds changelog for v2.3.0
**Checklist**
> chore(CHANGELOG): add changelogs for v2.3.0

- ci/upgrade/setup.sh
With travis-ci.org facing some infra issues, the tests may fail due to a slow VM or network. This PR increases the timeout for pods to come into running state. 
**Checklist**
> fix(travis): increase wait time for pods

- pkg/version/util.go
This PR adds 2.4.0 to the upgrade matrix 
**Checklist**
> chore(version): add 2.4.0 to upgrade matrix

- CHANGELOG.md
- changelogs/released/v2.4.0-RC1/74-shubham14bajpai
- changelogs/released/v2.4.0-RC1/75-shubham14bajpai
This PR adds changelog for v2.4.0
**Checklist**
> chore(CHANGELOG): add changelogs for v2.4.0

- docs/upgrade.md
This PR adds upgrade steps for v2.4.0
**Checklist**
> chore(upgrade): update upgrade README with 2.4.0 steps

- pkg/version/util.go
This PR adds 2.4.1 to the upgrade matrix
**Checklist**
> chore(version): add 2.4.1 to upgrade matrix

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- pkg/version/util.go
This PR updates the buildx action version to the latest stable release. This PR also updates the upgrade matrix with 2.5.0.
**Checklist**
> chore(build): update the buildx action verison

- CHANGELOG.md
This PR add changelogs for v2.5.0
**Checklist**
> chore(CHANGELOG): add changelogs for v2.5.0

- docs/upgrade.md
This PR adds steps for 2.5.0 upgrades.
**Checklist**
> chore(upgrade): update upgrade README with 2.5.0 steps

- ci/upgrade/setup.sh
- ci/upgrade/upgradetaskCRD.yaml
- go.mod
- go.sum
- pkg/version/util.go
- vendor/github.com/openebs/api/v2/pkg/apis/openebs.io/v1alpha1/upgradetask_types.go
- vendor/github.com/openebs/api/v2/pkg/util/env.go
- vendor/modules.txt
> chore(crd): update upgradeTask CRD to v1

- docs/upgrade.md
This PR updates upgrade README with 2.6.0 steps
**Checklist**
> chore(upgrade): update upgrade README with 2.6.0 steps

- CHANGELOG.md
- changelogs/released/v2.6.0-RC1/85-shubham14bajpai
- changelogs/released/v2.6.0-RC1/86-shubham14bajpai
- changelogs/released/v2.6.0-RC1/88-shubham14bajpai
> chore(CHANGELOG): add changelogs for v2.6.0

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- Makefile
- changelogs/unreleased/95-shubham14bajpai
- ci/migrate/sanity.sh
- ci/migrate/setup.sh
- ci/upgrade/cstor-operator.tmp.yaml
- ci/upgrade/sanity.sh
- ci/upgrade/setup.sh
This PR moves the unit and e2e tests to github actions.
Fixes #90 
**Checklist**
> chore(actions): move travis tests to github action

- docs/upgrade.md
This PR adds steps for 2.7.0 release
**Checklist**
> chore(upgrade): update upgrade README with 2.7.0 steps

- docs/upgrade.md
This PR updates upgrade README with 2.8.0 steps
**Checklist**
> chore(upgrade): update upgrade README with 2.8.0 steps

- docs/migration.md
- docs/upgrade.md
This PR adds documentation for upgrade and migration of jiva csi node
**Checklist**
> feat(docs): add jiva upgarde and migrate docs

- pkg/version/util.go
This PR adds support for 2.9.0 upgrades
**Checklist**
> chore(version): add 2.9.0 to upgrade matrix

- docs/upgrade.md
This PR adds upgrade steps for 2.9.0 release
**Checklist**
> chore(upgrade): update upgrade README with 2.9.0 steps

- README.md
This PR adds the jiva upgrade and migration links to the main README file
**Checklist**
> refact(README): add links to jiva upgarde and migration

- ci/upgrade/cstor/cstor-operator.tmp.yaml
- pkg/version/util.go
This PR adds the version 2.10.0 to upgrade matrix
> chore(version): add 2.10.0 to upgrade matrix

- cmd/migrate/executor/cstor_pool.go
Cherry-pick PR for #112 
**Checklist**
> fix(logs): remove label for listing cstorvolumes

- docs/upgrade.md
This PR adds upgrade steps for 2.10.0 release
**Checklist**
> chore(upgrade): update upgrade README with 2.10.0 steps

- e2e-tests/Dockerfile
Signed-off-by: nsathyaseelan <sathyaseelan.n@mayadata.io>
-  included the dependent package to install opeshift for ansible docker file
> refactor[e2e]: Included the dependent package for build the e2e image

- pkg/version/util.go
**What this PR does**: Adds 2.11.0 to the upgrade matrix. 
**Checklist**
> chore(version): add 2.10.1 & 2.11.0 to upgrade matrix

- docs/upgrade.md
**What this PR does**: 
Updates README with 2.11.0 upgrade steps
**Checklist**
> chore(upgrade): update upgrade README with 2.11.0 steps

- CONTRIBUTING.md
**What this PR does**: 
This PR adds a section to the CONTRIBUTING.md file where we mention the upgrade matrix bump which is required during releases. 
**Checklist**
> docs(contributing): add info regarding upgrade matrix

- ci/migrate/sanity.sh
- ci/upgrade/cstor/setup.sh
- pkg/version/util.go
> chore(ci): upgrade ndm-operator during cstor test

- e2e-tests/experiments/cspc_csi_upgrade/run_e2e_test.yml
- e2e-tests/experiments/cspc_csi_upgrade/test_vars.yml
Signed-off-by: nsathyaseelan <sathyaseelan.n@mayadata.io>
**Checklist**
> Refactor the test case to upgrade the cstor operator provision

- ci/upgrade/cstor/cstor-operator.tmp.yaml
- ci/upgrade/cstor/ndm-operator.yaml
- ci/upgrade/cstor/pool.tmp.yaml
- ci/upgrade/cstor/sanity.sh
- ci/upgrade/cstor/setup.sh
- ci/upgrade/cstor/volume.tmp.yaml
- pkg/upgrade/upgrader/cstor_cspi.go
- pkg/upgrade/upgrader/cstor_volume.go
- pkg/upgrade/upgrader/helper.go
Cherry-picks #124 
**Checklist**
> fix(upgrade): update cstor serviceAccount in cspi and target deployments

- e2e-tests/experiments/cspc_csi_upgrade/test.yml
Signed-off-by: nsathyaseelan <sathyaseelan.n@mayadata.io>
-  Included the task to remove the csidriver for 2.4.0 or lesser operator version while upgrading cstor operator
> refactor[e2e]: Included the task to remove the csidriver for 2.4.0 or lesser operator version while upgrading

- ci/upgrade/cstor/setup.sh
- ci/upgrade/jiva/setup.sh
Signed-off-by: shubham <shubham14bajpai@gmail.com>
Update chart yaml urls in ci tests
**Checklist**
> fix(ci): update operator chart urls

- e2e-tests/experiments/cspc_csi_upgrade/test_vars.yml
- e2e-tests/experiments/cstor-operator-provision/test_vars.yml
- e2e-tests/experiments/openebs-provision/test_vars.yml
Signed-off-by: nsathyaseelan <sathyaseelan.n@mayadata.io>
- This PR updates the changes made in the openebs/charts repo as part of this PR `https://github.com/openebs/charts/pull/255`
> refactor[e2e]: Updated the path for the provisioning the operator yaml

- docs/migration.md
Signed-off-by: shubham <shubham14bajpai@gmail.com>
Updates the jiva volume migration docs. Currently tested on ci images. Will update the PR status once newly tagged images are available.
**Checklist**
> fix(docs): update jiva migration docs with affinity changes

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- ci/migrate/sanity.sh
- ci/upgrade/cstor/sanity.sh
- ci/upgrade/jiva/sanity.sh
- pkg/version/util.go
Signed-off-by: Sahil Raja <sahilraja242@gmail.com>
- Adds 2.12.1 and 2.12.2 to the upgrade matrix.
Fixes 
**Checklist**
> chore(version): add 2.12.1 and 2.12.2 to upgrade matrix
