openebs/upgrade

pkg/upgrade/upgrader/cstor_cspc.go
pkg/upgrade/upgrader/cstor_volume.go
pkg/upgrade/upgrader/helper.go

This PR adds pre-upgrade checks for control plane operators.

refact(upgrade): add control plane checks in pre-upgrade

---

.travis.yml
Makefile
build/deploy.sh
cmd/migrate/executor/cstor_volume.go
cmd/migrate/executor/options.go
cmd/migrate/executor/setup_job.go
pkg/migrate/cstor/pool.go
pkg/migrate/cstor/volume.go
pkg/migrate/cstor/volume_operations.go

This PR adds support Cstor volume migration from external provisioner volume spec to CSI volume spec.
Example yaml:
```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
name: migrate-pvc-b12c1a29-3144-4ac9-8b89-2c1ff4998dc7
namespace: openebs
spec:
backoffLimit: 0
template:
spec:
#VERIFY the value of serviceAccountName is pointing to service account
serviceAccountName: openebs-maya-operator
containers:
- name:  migrate
args:
- "cstor-volume"
- "--pv-name=pvc-b12c1a29-3144-4ac9-8b89-2c1ff4998dc7"
#Following are optional parameters
#Log Level
- "--v=4"
#DO NOT CHANGE BELOW PARAMETERS
env:
- name: OPENEBS_NAMESPACE
valueFrom:
fieldRef:
fieldPath: metadata.namespace
tty: true
image: openebs/migrate-amd64:ci
restartPolicy: Never
---
``` …

feat(migrate): add support for cstor volume migration

---

pkg/migrate/cstor/volume.go

This PR adds code that forwards  ioworkers and queuedepth information from old volume to new volume.

fix(migrate): forward ioworkers and queuedepth from old to new volume

---

cmd/migrate/executor/cstor_volume.go
pkg/migrate/cstor/volume.go

This PR fixes the issue of version mismatch between CVC and its controller. As the CVC controller now handles the version population ref: https://github.com/openebs/cstor-operators/pull/106, removing the version details while creating CVC.
This PR also handles the case when podAffinity is set on the application: the affinity is removed as first to validate the volume health and once the volume becomes healthy the podAffinity is patched to the target deployment.

fix(migrate): remove version details from cvc creation

---

pkg/upgrade/upgrader/cstor_volume.go
pkg/version/util.go

This PR  handles upgrade for cstor volumes by adding PVC annotation to CVC and PVC label to CV and target deployment with reference to PRs : https://github.com/openebs/cstor-csi/pull/100 https://github.com/openebs/cstor-operators/pull/124 
This PR also enables RC upgrades for v1.12.0.
Note: PR contains some repetitive code to avoid dependencies between methods that can change in future upgrades.
Local test results:
before upgrade:
```sh
mayadata:upgrade$ k get cvc -oyaml
apiVersion: v1
items:
- apiVersion: cstor.openebs.io/v1
kind: CStorVolumeConfig
metadata:
annotations:
openebs.io/volume-policy: ""
openebs.io/volumeID: pvc-4b714a75-61d9-4ec0-93a5-7cb021511c1b
.........
mayadata:setup$ k get pod …
```

refact(upgrade): add labels and annotation for cstor volume

---

pkg/migrate/cstor/cspc_generator.go
pkg/migrate/cstor/cspc_generator_test.go

This PR fixes the striped spc raid group configuration bug where blockdevices are present in different raid groups while migrating to cspc.

fix(migration): fix striped raid group config while migrating

---

ci/upgrade/cstor-operator.tmp.yaml
ci/upgrade/pool.tmp.yaml
ci/upgrade/sanity.sh
ci/upgrade/setup.sh
ci/upgrade/test.sh
ci/upgrade/volume.tmp.yaml

This PR addresses the error caused when images are built with different IMAGE_ORG and the test fails due to missing tags or incompatibility between openebs & other org images

fix(travis): make upgrade sanity test configurable for different IMAGE_ORG

---

pkg/version/util.go

This PR adds 2.1.0 to upgrade matrix for upgrading to custom images tags for 2.1.0

chore(upgrade): add valid current versions for 2.1.0 upgrades

---

.travis.yml

This PR bumps travis go build version to 1.14.7 due to some security issues in older go versions.

chore(build): bump travis go build version to 1.14.7

---

pkg/migrate/cstor/volume.go

This PR updates the volume migration code to update the SC by only one job when multiple jobs running in parallel.
Local test performed:
Tested by launching 3 migration jobs in parallel and the job failure did not occur. Tried the same test 5 times and did not face the issue.

refact(migration): update volume migration to run in parallel

---

ci/migrate/pool.tmp.yaml
ci/migrate/test.sh
ci/migrate/volume.tmp.yaml

This PR fixes the issue of travis failures for forked repos where the imageorg of the images don't match with the `openebs`.
**Checklist**

fix(travis): update migrate jobs to use correct imageorg images

---

ci/migrate/migrationCRD.yaml
ci/migrate/setup.sh
cmd/migrate/executor/options.go
cmd/migrate/executor/resource.go
cmd/migrate/executor/setup_job.go
pkg/migrate/cstor/blockdevice_correction.go
pkg/migrate/cstor/interface.go
pkg/migrate/cstor/migrationtask.go
pkg/migrate/cstor/pool.go
pkg/migrate/cstor/volume.go

This PR adds support for status reports using a CR.
Fixes #40 
Tested locally with below CRs
Step1: migration CRD
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
name: migrationtasks.openebs.io
spec:
group: openebs.io
version: v1alpha1
scope: Namespaced
names:
plural: migrationtasks
singular: migrationtask
kind: MigrationTask
shortNames:
- mtask
```
Step2: created mtasks
```yaml
apiVersion: openebs.io/v1alpha1
kind: MigrationTask
metadata:
name: migrate-cstor-pool-cstor-pool-1
namespace: openebs
spec:
cstorPool:
spcName: cstor-pool-1
---
apiVersion: openebs.io/v1alpha1
kind: MigrationTask
metadata:
name: …
```

feat(migrate): add support for CR status reporting

---

Makefile.buildx.mk

Enabling more than two arch in the multi-arch builds
is resulting in increased build times as well as
intermittent failures in running the builds.
Limiting to two archs - amd64 and arm64 for now.
**Checklist**

refact(build): run only amd64 and arm64 builds

---

.github/workflows/build.yml
.github/workflows/release.yml
Makefile
build/migrate/migrate.Dockerfile
build/upgrade/upgrade.Dockerfile

The RELEASE_TAG env set in the action is not propagated to the buildx container. This PR fixes the same.
This PR also removes the deprecated envs
**Checklist**

fix(build): propagate RELEASE_TAG to buildx container

---

docs/migration.md
pkg/migrate/cstor/pool.go

This PR handles the scenario where the csp deployments are scaled up by mistake. The path to the lock file is different for csp and cspi deployments which leads to multiple simultaneous imports. Patching the `tmp` path while scaling down the csp deployment fixes this problem.
csp Volumes
```yaml
volumes:
- hostPath:
path: /dev
type: Directory
name: device
- hostPath:
path: /run/udev
type: Directory
name: udev
- hostPath:
path: /var/openebs/sparse/shared-cstor-pool
type: DirectoryOrCreate
name: tmp
- hostPath:
path: /var/openebs/sparse
type: DirectoryOrCreate
name: sparse
- hostPath:
path: /var/openebs/cstor-pool/cstor-pool
type: DirectoryOrCreate
name: storagepath
- emptyDir: {}
name: sockfile
```
cspi Volumes …

fix(migrate): update lock file path when csp is scaled down

---

pkg/upgrade/upgrader/cstor_cspi.go
pkg/upgrade/upgrader/cstor_volume.go
pkg/upgrade/upgrader/helper.go
pkg/upgrade/upgrader/helper_test.go

This PR adds the code to remove -amd64 suffix from the older cspc and cstor volume deployments which is no longer available with the multi-arch builds.
Fixes #84 
**Checklist**

feat(upgrade): remove the -amd64 suffix from images

---

changelogs/unreleased/96-shubham14bajpai
cmd/migrate/executor/cstor_pool.go
docs/migration.md
pkg/version/util.go

This PR adds logs and documentation about the multiple cstorvolume apis present in the cluster during migration. When the pools are migrated and volumes are still pending for migration there may be some volumes in the newer volumes in `cstorvolume.cstor.openebs.io` while some will still be in older api `cstorvolume.openebs.io`. The changes informs the user of such situations.
This PR also bumps the version matrix for 2.7.0
Ref: https://kubernetes.slack.com/archives/CUAKPFU78/p1614522935143200?thread_ts=1614470259.132700&cid=CUAKPFU78
**Checklist**

refact(migrate): improve logs and docs about multiple cstorvolume apis

---

cmd/migrate/executor/cstor_pool.go

This PR fixes the logs for migration as the cstorvolume don't have the label mentioned in the log
```
$ kubectl get cstorvolumes.openebs.io -n openebs --show-labels
NAME                                       STATUS   AGE   CAPACITY   LABELS
pvc-7019dcf7-cd9f-48b2-8846-df89c830ebea   Init     26m   2G         openebs.io/cas-template-name=cstor-volume-create-default-2.9.0,openebs.io/persistent-volume=pvc-7019dcf7-cd9f-48b2-8846-df89c830ebea,openebs.io/version=2.9.0
```
**Checklist**

fix(logs): remove label for listing cstorvolumes

---

ci/upgrade/cstor/cstor-operator.tmp.yaml
ci/upgrade/cstor/ndm-operator.yaml
ci/upgrade/cstor/pool.tmp.yaml
ci/upgrade/cstor/sanity.sh
ci/upgrade/cstor/setup.sh
ci/upgrade/cstor/volume.tmp.yaml
pkg/upgrade/upgrader/cstor_cspi.go
pkg/upgrade/upgrader/cstor_volume.go
pkg/upgrade/upgrader/helper.go

This PR fixes the service account change issue. In the operator yamls before 2.8.0 the service account used was `openebs-maya-operator` and the clusterrole/clusterrolebinding were named` openebs-cstor-operator`. From 2.8.0 the service account was renamed to `openebs-cstor-operator` and the clusterrole/clusterrolebinding are updated with the . Now the older deployments have the old service account but the clusterrole/clusterrolebinding point to the new service account. Patching the deployments with the new service account name fixes the problem.
**Checklist**

fix(upgrade): update cstor serviceAccount in cspi and target deployments

---

README.md
docs/upgrade.md

Adds a note under the prerequisites section **informing
Day-2-Operations doesn't support** when the control plane
and pools/volumes in different version.
No
**Checklist**
Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>

chore(doc): add note about day-2-operations when control plane alone is upgraded
